# Generated by Django 6.0.5 on 2026-05-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'subject')},
        ),
    ]
