# Generated by Django 6.0.5 on 2026-05-12 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenue_effective', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('tenue', 'Tenue'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('date_heure', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'defenses',
            },
        ),
        migrations.CreateModel(
            name='DefenseObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('critere', models.CharField(blank=True, choices=[('qualite_scientifique', 'Qualité scientifique'), ('qualite_redactionnelle', 'Qualité rédactionnelle'), ('presentation_orale', 'Présentation orale'), ('maitrise_sujet', 'Maîtrise du sujet'), ('recommandations', 'Recommandations')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'defense_observations',
            },
        ),
        migrations.CreateModel(
            name='DefenseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=150, null=True)),
                ('date_session', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
            ],
            options={
                'db_table': 'defense_sessions',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_document', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_travail', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_presentation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_reponses', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_finale', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mention', models.CharField(blank=True, choices=[('Passable', 'Passable'), ('Assez_Bien', 'Assez Bien'), ('Bien', 'Bien'), ('Tres_Bien', 'Très Bien'), ('Excellent', 'Excellent')], max_length=30, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('validee', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'juries',
            },
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_dans_jury', models.CharField(choices=[('president', 'Président'), ('encadrant', 'Encadrant'), ('superviseur', 'Superviseur'), ('membre', 'Membre'), ('rapporteur', 'Rapporteur')], max_length=30)),
            ],
            options={
                'db_table': 'jury_members',
            },
        ),
    ]
