# Generated by Django 6.0.5 on 2026-05-12 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('defenses', '0001_initial'),
        ('memoires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='memoire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense', to='memoires.memoire'),
        ),
        migrations.AddField(
            model_name='defenseobservation',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='defense_observations_ecrites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defenseobservation',
            name='defense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_observations', to='defenses.defense'),
        ),
        migrations.AddField(
            model_name='defensesession',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='defense_sessions', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='defense',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='defenses', to='defenses.defensesession'),
        ),
        migrations.AddField(
            model_name='grade',
            name='defense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='defenses.defense'),
        ),
        migrations.AddField(
            model_name='jury',
            name='defense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='defenses.defense'),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='defenses.jury'),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jury_participations', to='accounts.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='jurymember',
            unique_together={('jury', 'teacher')},
        ),
    ]
