# Generated by Django 6.0.5 on 2026-05-12 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('plan', 'Plan'), ('version_intermediaire', 'Version intermediaire'), ('version_finale', 'Version finale'), ('annexe', 'Annexe'), ('fiche_validation', 'Fiche de validation')], max_length=50, null=True)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_stockage', models.CharField(max_length=500)),
                ('version', models.IntegerField(default=1)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=150)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_faire', 'A faire'), ('en_cours', 'En cours'), ('valide', 'Valide'), ('depasse', 'Depasse')], default='a_faire', max_length=20)),
            ],
            options={
                'db_table': 'milestones',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('type_observation', models.CharField(blank=True, choices=[('commentaire', 'Commentaire'), ('recommandation', 'Recommandation'), ('correction', 'Correction')], max_length=30, null=True)),
                ('date_observation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'observations',
            },
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('statut_avancement', models.CharField(choices=[('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('abandonne', 'Abandonné'), ('finalise', 'Finalisé')], default='en_cours', max_length=20)),
                ('soutenable', models.BooleanField(default=False)),
                ('date_validation_soutenabilite', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memoire', to='accounts.student')),
            ],
            options={
                'db_table': 'memoires',
            },
        ),
    ]
