# Generated by Django 6.0.5 on 2026-05-12 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memoires', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memoire', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='document',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='memoires.memoire'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='memoires.memoire'),
        ),
        migrations.AddField(
            model_name='observation',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='observations_ecrites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='memoires.memoire'),
        ),
    ]
