# Generated by Django 6.0.5 on 2026-05-12 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('archivee', 'Archivée')], default='en_cours', max_length=20)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('date_limite_sujets', models.DateField(blank=True, null=True)),
                ('date_limite_candidatures', models.DateField(blank=True, null=True)),
                ('date_limite_documents', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ferme', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear')),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['academic_year', 'libelle'],
            },
        ),
    ]
